### ISSUE TITLE
Addition and removal of rule to a binded interface keeps hardware and app out of sync.

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#1]
If you add a new rule after binding, Get results in no binding. But, hardware is in right state. Similarly, I checked for the removal of rule, when its already binded. Somehow, app and hardware are in out of sync.

**Comment by jeffyin-dell** [comment]
Is this resolved? Issue was opened a month ago and was transferred from the deprecated repo, so want to make sure this is still being tracked if needs to be, or closed if it doesn't.

**Comment by justinejose91** [comment]
@Tejaswi-Goel is verifying it. Will move accordingly.

**Comment by jeffyin-dell** [comment]
@Tejaswi-Goel please add your most recent findings here

**Comment by Tejaswi-Goel** [comment]
I tried configuring ingress/egress ACL on interfaces through CLI, even though CLI returned success, I could not see any ingress and egress configuration in hardware. I have asked Broadcom team to further look into this issue. @sachinholla @PrabhuSreenivasan

**Comment by sachinholla** [comment]
hi @Tejaswi-Goel , I could not recreate the "hardware programming not happening" case. But I could recreate the original observations of Justin -- when new new rule is added to an already bound ACL, it is replacing the old rules from hardware. I feel this issue is different from what you observed (hardware not programmed). Can you provide exact sequence of CLIs used? Also CONFDB and ASICDB dumps for ACL related entries.

**Comment by sachinholla** [comment]
CLI sends PATCH request when user enters "ip access-list <NAME>" submode. ACL app is doing blind mod_entry and redis blindly sends out keyspace notification for ACL table entry even if the old values are same as the new values. Orcagent is cleaning up old entries upon this notification -- limitation of orcagent. Old entries are not re-created since ACL_RULE is not getting notified here (since it is not getting touched). Looks like orcagent is not designed for incremental ACL changes. Fixing orcaganet logic is tricky at this stage, hence ACL app will be enhanced to do mod_entry only of something is changing.

Workaround - none :(

**Comment by maheshwari-mayank** [comment]
Issue fixed.
