### ISSUE TITLE
ygotTarget Object returned is null for leaf uri by the request binder API

### ISSUE THREAD

**Issue by ranjinidn** [project-arlo/sonic-mgmt-framework#181]
We do not get a valid ygotTarget object for a leaf request.
The below function in translib.go is where we get the ygot target.
func appInitialize(app *appInterface, appInfo *appInfo, path string, payload *[]byte, opCode int) error {
….
….
                ygotStruct, **ygotTarget**, err := getRequestBinder(&path, payload, opCode, &(appInfo.ygotRootType)).unMarshall()
                if err != nil {
                        log.Info("Error in request binding: ", err)
                        return err
                }

                data := appData{path: path, payload: input, ygotRoot: ygotStruct, **ygotTarget**: ygotTarget}
                (*app).initialize(data)
        }

The same ygotTarget is used by the common_app to Unmarshall the json payload generated by the transformer.

targetObj, _ := (*app.ygotTarget).(ygot.GoStruct)
    if targetObj != nil {
err = ocbinds.Unmarshal(payload, targetObj)
..
   }

The CLI reads the data set to the ygotStructures (which are not filled because the ocbinds.Unmarshal is not called) and hence they get null data.

Opened this issue to solve this problem.

**Comment by mbalachandar** [comment]
Hi Ranjini

For GET request for the target leaf node, there will not be any payload, since there is no value for the leaf to fill in, then target node will be nil only.

If you want to know target node name, you can use this function
getNodeName() in path_utils.go to get the node name of the target.

Also my doubt is for GET request, there will not be any payload, then what we are trying to unmarshal in case of transformer in common_app.

targetObj, _ := (*app.ygotTarget).(ygot.GoStruct)
if targetObj != nil {
err = ocbinds.Unmarshal(payload, targetObj)
..
}
Thanks
Balachandar

**Comment by mbalachandar** [comment]
Ok, I understand that its for the response case what transformer is looking for. You need to get the parent node of the target and does the unmarshal, since the leaf will be int, string, so you can call unmarshal on the leaf object. You can use the getParentNode() from path_utils.go to get the parent node of the target.

**Comment by mbalachandar** [comment]
* so you cannot call unmarshal on the leaf object. You can use the getParentNode() from path_utils.go to get the parent node of the target.

**Comment by ranjinidn** [comment]
Thank you. Will look into this.
