### ISSUE TITLE
Transformer passing string value instead of int and this results in unmarshal failure

### ISSUE THREAD

**Issue by anand-kumar-subramanian** [project-arlo/sonic-mgmt-framework#253]
Request:
curl -X GET "https://$DUTIP/restconf/data/ietf-ptp:ptp" -H "accept: application/yang-data+json" -k

syslog:
Nov  5 21:58:42.198186 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196065      54 xlate.go:366] Payload generated:{"instance-list":[{"current-ds":{"mean-path-delay":"0.0","offset-from-master":"0.0","steps-removed":0},"default-ds":{"clock-quality":{"clock-accuracy":0,"clock-class":0,"offset-scaled-log-variance":0},"domain-number":0,"number-ports":0,"priority1":0,"priority2":0,"slave-only":true,"two-step-flag":true},"instance-number":0,"parent-ds":{"grandmaster-clock-quality":{"clock-accuracy":254,"clock-class":248,"offset-scaled-log-variance":65535},"grandmaster-identity":"PCyZ//7wxYA=","grandmaster-priority1":0,"grandmaster-priority2":0,"observed-parent-clock-phase-change-rate":2147483647,"observed-parent-offset-scaled-log-variance":65535,"parent-port-identity":{"clock-identity":"PCyZ//7wxYA=","port-number":0},"parent-stats":false},"port-ds-list":[{"announce-receipt-timeout":3,"log-announce-interval":1,"log-min-delay-req-interval":0,"log-min-pdelay-req-interval":0,"log-sync-interval":0,"peer-mean-path-delay":"0","port-number":1,"port-state":"faulty","version-number":2}],"time-properties-ds":{"current-utc-offset":37}}],"transparent-clock-default-ds":{"delay-mechanism":"e2e","number-ports":0,"primary-domain":0},"transparent-clock-port-ds-list":[{"faulty-flag":true,"log-min-pdelay-req-interval":0,"peer-mean-path-delay":"0","port-number":0}]}
Nov  5 21:58:42.198186 sonic INFO mgmt-framework#supervisord: rest-server E1105 21:58:42.196282      54 common_app.go:223] ocbinds.Unmarshal()  failed. error:error parsing 0.0 for schema mean-path-delay: strconv.ParseInt: parsing "0.0": invalid syntax
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196298      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:0>, Opts: { DBNo: 0, InitIndicator: , TableNameSeparator: :, KeySeparator: : , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196327      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:1>, Opts: { DBNo: 1, InitIndicator: , TableNameSeparator: |, KeySeparator: | , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196345      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:2>, Opts: { DBNo: 2, InitIndicator: , TableNameSeparator: :, KeySeparator: : , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196362      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:3>, Opts: { DBNo: 3, InitIndicator: , TableNameSeparator: |, KeySeparator: | , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196379      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:4>, Opts: { DBNo: 4, InitIndicator: , TableNameSeparator: |, KeySeparator: | , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196497      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:5>, Opts: { DBNo: 5, InitIndicator: , TableNameSeparator: |, KeySeparator: | , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
Nov  5 21:58:42.198214 sonic INFO mgmt-framework#supervisord: rest-server I1105 21:58:42.196524      54 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:6>, Opts: { DBNo: 6, InitIndicator: , TableNameSeparator: |, KeySeparator: | , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
/tmp/dbToYangJson.txt:
{"instance-list":[{"current-ds":{"mean-path-delay":"0.0","offset-from-master":"0.0","steps-removed":0},"default-ds":{"clock-quality":{"clock-accuracy":0,"clock-class":0,"offset-scaled-log-variance":0},"domain-number":0,"number-ports":0,"priority1":0,"priority2":0,"slave-only":true,"two-step-flag":true},"instance-number":0,"parent-ds":{"grandmaster-clock-quality":{"clock-accuracy":254,"clock-class":248,"offset-scaled-log-variance":65535},"grandmaster-identity":"PCyZ//7wxYA=","grandmaster-priority1":0,"grandmaster-priority2":0,"observed-parent-clock-phase-change-rate":2147483647,"observed-parent-offset-scaled-log-variance":65535,"parent-port-identity":{"clock-identity":"PCyZ//7wxYA=","port-number":0},"parent-stats":false},"port-ds-list":[{"announce-receipt-timeout":3,"log-announce-interval":1,"log-min-delay-req-interval":0,"log-min-pdelay-req-interval":0,"log-sync-interval":0,"peer-mean-path-delay":"0","port-number":1,"port-state":"faulty","version-number":2}],"time-properties-ds":{"current-utc-offset":37}}],"transparent-clock-default-ds":{"delay-mechanism":"e2e","number-ports":0,"primary-domain":0},"transparent-clock-port-ds-list":[{"faulty-flag":true,"log-min-pdelay-req-interval":0,"peer-mean-path-delay":"0","port-number":0}]}
redis:
127.0.0.1:6379[4]> keys PTP*
1) "PTP_TC_PORT|Ethernet0"
2) "PTP_PARENTDS|GLOBAL"
3) "PTP_PORT|GLOBAL|Ethernet0"
4) "PTP_INSTANCE|GLOBAL"
5) "PTP_TC_CLOCK|GLOBAL"
6) "PTP_CURRENTDS|GLOBAL"
7) "PTP_TIMEPROPDS|GLOBAL"
8) "PTP_CLOCK|GLOBAL"
127.0.0.1:6379[4]> hgetall "PTP_CURRENTDS|GLOBAL"
1) "steps-removed"
2) "0"
3) "mean-path-delay"
4) "0"
5) "offset-from-master"
6) "0"
Collapse

**Comment by amrutasali** [comment]
Analysis in progress

**Comment by amrutasali** [comment]
@anand-kumar-subramanian 
I tried to reproduce the issue with the data that you have provided above for Redis PTP_CURRENTDS table,  but  there is no failure seen, here is the output from dlv :

We are using transformer-phase2 branch, I hope on your end its the same branch.

I1107 00:58:54.970999    2830 **xlate.go:366**] Payload generated:{"instance-list":[{"current-ds":{**"mean-path-delay":"0"**,"steps-removed":266},"default-ds":{"clock-quality":{"clock-accuracy":4,"clock-class":3,"offset-scaled-log-variance":0},"domain-number":16,"priority1":222,"priority2":111},"instance-number":0,"parent-ds":{"grandmaster-clock-quality":{"clock-accuracy":22,"clock-class":54,"offset-scaled-log-variance":234},"grandmaster-priority1":8,"grandmaster-priority2":16,"observed-parent-offset-scaled-log-variance":33,"parent-port-identity":{"port-number":0}},"time-properties-ds":{"current-utc-offset":4}}],"transparent-clock-default-ds":{"number-ports":23,"primary-domain":20},"transparent-clock-port-ds-list":[{"faulty-flag":true,"log-min-pdelay-req-interval":23,"peer-mean-path-delay":"0","port-number":0}]}
I1107 00:58:55.021799    2830 **translibtest.go:62] Response payload** ={"ietf-ptp:ptp":{"instance-list":[{"current-ds":{"mean-path-delay":"0","steps-removed":266},"default-ds":{"clock-quality":{"clock-accuracy":4,"clock-class":3,"offset-scaled-log-variance":0},"domain-number":16,"priority1":222,"priority2":111},"instance-number":0,"parent-ds":{"grandmaster-clock-quality":{"clock-accuracy":22,"clock-class":54,"offset-scaled-log-variance":234},"grandmaster-priority1":8,"grandmaster-priority2":16,"observed-parent-offset-scaled-log-variance":33,"parent-port-identity":{"port-number":0}},"time-properties-ds":{"current-utc-offset":4}}],"transparent-clock-default-ds":{"number-ports":23,"primary-domain":20},"transparent-clock-port-ds-list":[{"faulty-flag":true,"log-min-pdelay-req-interval":23,"peer-mean-path-delay":"0","port-number":0}]}}
Process 2830 has exited with status 0
(dlv) 

Unless there is 0.0 value manually populatated using redis-cli in  Redis DB for mean-path-delay this shouldn't happen because CVL will never allow float value(0.0) for int64 value in sonic-yang.

Also the yang data-type for mean-path-delay in ietf-ptp.yang is int64 which according to ygot(**https://github.com/openconfig/ygot/blob/master/ytypes/util_types.go#L182**) should be string when the data is in **JSON format**, hence from transformer we are sending it as string(seen in the log with line **xlate.go:Payload generated**)

The  error  in logs provided : "error parsing 0.0 for schema mean-path-delay: **strconv.ParseInt**: parsing "0.0": invalid syntax."  is complaining about "**invalid syntax**".
The function strconv.ParseInt()  is trying to convert **string value to int** value and **int value**(yang type for mean-path-delay) **cannot have a decimal point in it**The value 0.0 has a decimal point in it and hence the complain "invalid synatx".

Also note that the value for field **peer-mean-path**(yang data-type both in OC and sonic yang are same ) **ocbinds doesn't comlpain even though the json paylod from transformer has string type for it**.

So the conclusion is Redis DB cannot have a float value for an int64 data-type    and as per ygot int64 has to be string when in JSON format as per above github link on util_types.go and transformer does send it as string.
Please double check your redis DB.

**Comment by anand-kumar-subramanian** [comment]
@amrutasali No Amruta we are using our own internal branch which is in sync with the github master branch. I communicated this to Mari but I will communicate the same to you again here. We took the transformer phase 2 code and tested it here and everything worked for us as well. We were expecting the code changes to come from master github branch. Once it arrived, we tested it (assuming everything will work and we could checkin)and we are getting the above error. There is some code changes that has not made it to the master github branch and because of this we are having this issue.

**Comment by amrutasali** [comment]
@anand-kumar-subramanian I  tried on master branch I don't see any issue , here is the git status(from my workspace) and dlv output 

asali@dvss-server-26:~/snc_mst/sonic-mgmt-framework/src/translib/test$ git status
On branch master
Your branch is up to date with '**origin/master**'.

ntracked files:
  (use "git add <file>..." to include in what will be committed)

	../../../models/yang/annotations/ietf-ptp-annot.yang
       ../../../models/yang/ietf-ptp.yang
	../../../models/yang/sonic/sonic-ptp.yang
        ../transformer/xfmr_ptp.go
no changes added to commit (use "git add" and/or "git commit -a")
asali@dvss-server-26:~/snc_mst/sonic-mgmt-framework/src/translib/test$

asali@dvss-server-26:~/snc_mst/sonic-mgmt-framework/src/translib/test$ dlv exec /home/asali/snc_mst/sonic-mgmt-framework/src/translib/test/gdb_sandbox -- -o "get" -u "/ietf-ptp:ptp" -p "/home/asali/snc_mst/sonic-mgmt-framework/src/translib/test/acl-sonic/01_create_MyACL1_1Rule.json" -logtostderr
Type 'help' for list of commands.
(dlv) 
I1107 19:26:21.091490   29318 **xlate.go**:366] Payload generated:{"instance-list":[{"current-ds":{"**mean-path-delay":"0**","steps-removed":266},"default-ds":{"clock-quality":{"clock-accuracy":4,"clock-class":3,"offset-scaled-log-variance":0},"domain-number":16,"priority1":222,"priority2":111},"instance-number":0,"parent-ds":{"grandmaster-clock-quality":{"clock-accuracy":22,"clock-class":54,"offset-scaled-log-variance":234},"grandmaster-priority1":8,"grandmaster-priority2":16,"observed-parent-offset-scaled-log-variance":33,"parent-port-identity":{"port-number":0}},"time-properties-ds":{"current-utc-offset":4}}],"transparent-clock-default-ds":{"number-ports":23,"primary-domain":20},"transparent-clock-port-ds-list":[{"faulty-flag":true,"log-min-pdelay-req-interval":23,"peer-mean-path-delay":"0","port-number":0}]}
I1107 19:26:21.145425   29318 **translibtest.go**:62] Response payload ={"ietf-ptp:ptp":{"instance-list":[{"current-ds":{"mean-path-delay":"0","steps-removed":266},"default-ds":{"clock-quality":{"clock-accuracy":4,"clock-class":3,"offset-scaled-log-variance":0},"domain-number":16,"priority1":222,"priority2":111},"instance-number":0,"parent-ds":{"grandmaster-clock-quality":{"clock-accuracy":22,"clock-class":54,"offset-scaled-log-variance":234},"grandmaster-priority1":8,"grandmaster-priority2":16,"observed-parent-offset-scaled-log-variance":33,"parent-port-identity":{"port-number":0}},"time-properties-ds":{"current-utc-offset":4}}],"transparent-clock-default-ds":{"number-ports":23,"primary-domain":20},"transparent-clock-port-ds-list":[{"faulty-flag":true,"log-min-pdelay-req-interval":23,"peer-mean-path-delay":"0","port-number":0}]}}
Process 29318 has exited with status 0
(dlv) 


No where the value "0.0"   is seen unless someone manually populates in Redis DB because CVL will not allow 0.0 value for int64

Also note that the peer-mean-path field has no issue.

The change that is not in master is for sonic yang key leaf values(mclag issue - https://github.com/project-arlo/sonic-mgmt-framework/issues/241) .
There is no change for OC yang, non-default leaf values ,in data-type conversion area

**Comment by anand-kumar-subramanian** [comment]
We found the problem. The issue was the data was coming from stateDB and not configDB. And the stateDB had "0.0" in it.
